services:

  joy2twist:
    image: husarion/joy2twist:humble-nightly
    restart: unless-stopped
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/input/js0
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      bash -c
      "ros2 launch 
      joy2twist gamepad_controller.launch.py
      joy2twist_params_file:=$(ros2 pkg prefix joy2twist)/share/joy2twist/config/joy2twist_panther.yaml"
