version: v3.0
allowlist:
  - name: "rt/robot1/cmd_vel"
    type: "geometry_msgs::msg::dds_::Twist_"
blocklist: []
builtin-topics: []
participants:
  - name: DockerParticipant
    kind: local
    domain: 0
    whitelist-interfaces:
      - 172.17.0.1   # docker0 IP address
  - name: HostParticipant
    kind: local
    domain: 0
    ignore-participant-flags: filter_different_and_same_process # Discovery traffic from own host is discarded