services:

  joy2twist:
    image: husarion/joy2twist:galactic
    restart: unless-stopped
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/input/js0
    environment:
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes: 
      - ../joy2twist/config/joy2twist_panther.yaml:/joy2twist.yaml
    command: >
      ros2 launch
      joy2twist gamepad_controller.launch.py
      joy2twist_params_file:=/joy2twist.yaml

  bridge:
    image: husarion/ros:galactic-ros1-bridge
    restart: unless-stopped
    network_mode: host
    ipc: host
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
    command: >
      ros2 run
      ros1_bridge dynamic_bridge
