services:

  ros-master:
    image: ros:noetic-ros-core
    restart: unless-stopped
    command: stdbuf -o L roscore

  joy2twist:
    image: husarion/joy2twist:noetic
    restart: unless-stopped
    tty: true
    devices:
      - /dev/input/js0
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    volumes: 
      - ../joy2twist/config/joy2twist.yaml:/joy2twist.yaml
    command: >
      roslaunch --wait
      joy2twist gamepad_controller.launch 
      joy2twist_params_file:=/joy2twist.yaml

  rosbot:
    image: husarion/rosbot:noetic
    restart: unless-stopped
    tty: true
    devices:
      - ${SERIAL_PORT}
    environment:
      - SERIAL_PORT
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      roslaunch --wait
      rosbot_bringup rosbot_docker.launch
