services:

  joy2twist:
    image: husarion/joy2twist:noetic
    restart: unless-stopped
    tty: true
    network_mode: host
    ipc: host
    devices:
      - /dev/input/js0
    environment:
      - ROS_IP=10.15.20.2
      - ROS_MASTER_URI=http://10.15.20.2:11311
    volumes:
      - ../joy2twist/config/joy2twist.yaml:/ros_ws/src/joy2twist/joy2twist/config/joy2twist.yaml
    command: >
      roslaunch --wait
      joy2twist gamepad_controller.launch docker:=true
