services:

  ros-master:
    image: ros:melodic-ros-core
    restart: unless-stopped
    command: stdbuf -o L roscore

  joy2twist:
    image: husarion/joy2twist:melodic
    restart: unless-stopped
    tty: true
    devices:
      - /dev/input/js0
    environment:
      - ROS_MASTER_URI=http://ros-master:11311
    volumes: 
      - ../joy2twist/config/joy2twist.yaml:/ros_ws/src/joy2twist/joy2twist/config/joy2twist.yaml
    command: >
      roslaunch --wait 
      joy2twist gamepad_controller.launch docker:=true

  rosbot:
    image: husarion/rosbot:melodic
    restart: unless-stopped
    tty: true
    devices:
      - ${SERIAL_PORT}
    environment:
      - SERIAL_PORT
      - ROS_MASTER_URI=http://ros-master:11311
    command: >
      roslaunch --wait
      rosbot_bringup rosbot_docker.launch
